
package com.jc.gymbasicsystemfront.views;


import com.jc.gymbasicsystemfront.dto.auth.IAuthUserDetails;
import com.jc.gymbasicsystemfront.exceptions.AuthException;
import com.jc.gymbasicsystemfront.services.AuthService;
import com.jc.gymbasicsystemfront.views.employee.EmployeeView;
import com.jc.gymbasicsystemfront.views.member.MemberView;
import com.jc.gymbasicsystemfront.views.plan.PlanView;
import com.jc.gymbasicsystemfront.views.promotion.PromotionView;
import com.jc.gymbasicsystemfront.views.reports.BarReportView;
import com.jc.gymbasicsystemfront.views.subscription.SubscriptionView;
import java.io.IOException;
import javax.swing.JFrame;


public class HomeView extends javax.swing.JFrame {

    private AuthService authService;
    
    public HomeView() {
        initComponents();
        setTitle("Gym System");
        
        authService = new AuthService();
        validateRoleAuthentication();
    }
    
    private void validateRoleAuthentication (){
    
        try {
            IAuthUserDetails authUser = authService.checkAuth();
            System.out.println(authUser);
            if (authUser.getRole().equals("USER")){
                jmiMember.setVisible(false);
                jmiEmployee.setVisible(false);
            
            }
            
        } catch (AuthException e) {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mLogout = new javax.swing.JMenuItem();
        mBtnMantenedor = new javax.swing.JMenu();
        jmiEmployee = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmiMember = new javax.swing.JMenuItem();
        miPromotion = new javax.swing.JMenuItem();
        jmiPlan = new javax.swing.JMenuItem();
        jmNewSubscirption = new javax.swing.JMenu();
        jmNewSubscription = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmReports = new javax.swing.JMenu();
        jmiReports = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu6.setText("jMenu6");

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        jMenuItem5.setText("jMenuItem5");

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gym System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jMenu3.setText("Inicio");

        mLogout.setText("Salir");
        mLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogoutActionPerformed(evt);
            }
        });
        jMenu3.add(mLogout);

        jMenuBar2.add(jMenu3);

        mBtnMantenedor.setText("Mantenerdor");

        jmiEmployee.setText("Empleados");
        jmiEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmployeeActionPerformed(evt);
            }
        });
        mBtnMantenedor.add(jmiEmployee);

        jMenuItem3.setText("Usuarios");
        mBtnMantenedor.add(jMenuItem3);

        jmiMember.setText("Miembros");
        jmiMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMemberActionPerformed(evt);
            }
        });
        mBtnMantenedor.add(jmiMember);

        miPromotion.setText("Promociones");
        miPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPromotionActionPerformed(evt);
            }
        });
        mBtnMantenedor.add(miPromotion);

        jmiPlan.setText("Planes");
        jmiPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlanActionPerformed(evt);
            }
        });
        mBtnMantenedor.add(jmiPlan);

        jMenuBar2.add(mBtnMantenedor);

        jmNewSubscirption.setText("Suscripciones");

        jmNewSubscription.setText("Nueva suscripcion");
        jmNewSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewSubscriptionActionPerformed(evt);
            }
        });
        jmNewSubscirption.add(jmNewSubscription);

        jMenuBar2.add(jmNewSubscirption);

        jMenu7.setText("Asistencia");
        jMenuBar2.add(jMenu7);

        jmReports.setText("Reportes");

        jmiReports.setText("Reportes");
        jmiReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReportsActionPerformed(evt);
            }
        });
        jmReports.add(jmiReports);

        jMenuBar2.add(jmReports);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmployeeActionPerformed
        EmployeeView employeeView = new EmployeeView();
        employeeView.setLocationRelativeTo(null);
        employeeView.setVisible(true);
    }//GEN-LAST:event_jmiEmployeeActionPerformed

    private void miPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPromotionActionPerformed
        PromotionView promotionView = new PromotionView();
        promotionView.setVisible(true);
        promotionView.setLocationRelativeTo(null);
    }//GEN-LAST:event_miPromotionActionPerformed

    private void jmNewSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewSubscriptionActionPerformed
        SubscriptionView subscriptionView = new SubscriptionView();
        subscriptionView.setVisible(true);
        subscriptionView.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmNewSubscriptionActionPerformed

    private void mLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogoutActionPerformed
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mLogoutActionPerformed

    private void jmiReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReportsActionPerformed
        BarReportView barReportView = new BarReportView();
        barReportView.setVisible(true);
        barReportView.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiReportsActionPerformed

    private void jmiMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMemberActionPerformed
        MemberView memberView = new MemberView();
        
        memberView.setVisible(true);
        memberView.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiMemberActionPerformed

    private void jmiPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlanActionPerformed
       PlanView planView = new PlanView();
       planView.setVisible(true);
       planView.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    public void getPosts() throws IOException {
//         GymBasicSystemApi gymApi = new GymBasicSystemApi("http://localhost:8083/api/v1/auth/login", new TokenManager());
//        
//       java.lang.reflect.Type postListType = new TypeToken<List<Post>>(){}.getType();  
//        List<Post> posts = gymApi.get("/posts", postListType, false);
//        System.out.println("Posts" + posts);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmNewSubscirption;
    private javax.swing.JMenuItem jmNewSubscription;
    private javax.swing.JMenu jmReports;
    private javax.swing.JMenuItem jmiEmployee;
    private javax.swing.JMenuItem jmiMember;
    private javax.swing.JMenuItem jmiPlan;
    private javax.swing.JMenuItem jmiReports;
    private javax.swing.JMenu mBtnMantenedor;
    private javax.swing.JMenuItem mLogout;
    private javax.swing.JMenuItem miPromotion;
    // End of variables declaration//GEN-END:variables
}
